name: CI

on:
  push:
    branches:
      - develop
      - feature/**
      - release/**
      - hotfix/**
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  # Generalized CI job for all branches
  ci:
    runs-on: ubuntu-latest

    # Avoid redundant runs when the workflow is triggered by both push and pull_request
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref != github.head_ref)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for branches and tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run Flake8 (warn only)
        run: |
          poetry run flake8 . || echo "flake8 warnings ignored"
      - name: Run pylint (warn only)
        run: |
          poetry run pylint azure_rm_proxy || echo "pylint warnings ignored"
      - name: Run Black (warn only)
        run: |
          poetry run black --check . || echo "black warnings ignored"

      - name: Run mypy (warn only)
        run: |
          poetry run mypy azure_rm_proxy || echo "mypy warnings ignored"

      - name: Run tests
        run: poetry run pytest --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true